### ISSUE TITLE
Exception when running multiple connect instances `state is not synced for topic [ ] partition [ ]`

### ISSUE THREAD

**Issue by danifullview** [ClickHouse/clickhouse-kafka-connect#103]
### Describe the bug
We're running the sink connector inside k8s.
When we increase the number of worker instances, all the tasks are crashing w/ this exception:
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
...
Caused by: java.lang.RuntimeException: state is not synced for topic [events] partition [2]
	at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:165)
	at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
	at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
```
### Steps to reproduce
1. Create a docker image like:
```
FROM --platform=linux/arm64 confluentinc/cp-kafka-connect:7.4.0
ENV CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
RUN confluent-hub install --no-prompt clickhouse/clickhouse-kafka-connect:0.0.10-beta
```
2. Deploy to k8s
3. Configure the worker using the config:
```
{
  "connector.class": "com.clickhouse.kafka.connect.ClickHouseSinkConnector",
  "tasks.max": "1",
  "topics": "events",
  "key.ignore": "true",
  "ssl": "true",
  "hostname": "<redacted>",
  "database": "<redacted>",
  "password": "<redacted>",
  "port": "8443",
  "consumer.override.max.poll.records": "100000",
  "value.converter.schemas.enable": "false",
  "consumer.override.max.partition.fetch.bytes": "102400000",
  "exactlyOnce": "true",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "username": "default"
}
```
4. Scale up the deployment, to more than 1 instances

### Error log
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:618)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: state is not synced for topic [events] partition [2]
	at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:165)
	at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
	at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	... 11 more
```

#### Environment
* Kafka-Connect version: `7.4.0`
* Kafka Connect configuration: `default configs`
* Kafka version: `-`
* Kafka environment: `cloud (Confluent)`
* OS: `-`

#### ClickHouse server
* ClickHouse Server version: `23.3 (cloud)`
* ClickHouse Server non-default settings, if any:

**Comment by mzitnik** [comment]
@danifullview

**Comment by danifullview** [comment]
Thank you @mzitnik .
Truncating the table did the trick.

Another issue I'm having now, is this:
I have do a clean kafka connect deployment that has two instances.

I connect to one of the pods, and create the clickhouse worker task, using the configs in the 1st post.
The pod I'm connecting to will create the task while the 2nd pod will start to throw lots of errors like this:
```
[2023-05-12 08:34:46,609] INFO EnrichedConnectorConfig values: 
	config.action.reload = restart
	connector.class = com.clickhouse.kafka.connect.ClickHouseSinkConnector
	errors.deadletterqueue.context.headers.enable = false
	errors.deadletterqueue.topic.name = 
	errors.deadletterqueue.topic.replication.factor = 3
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = null
	name = ClickHouseSinkConnector
	predicates = []
	tasks.max = 1
	topics = [events]
	topics.regex = 
	transforms = []
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig)
[2023-05-12 08:34:46,621] ERROR Error forwarding REST request (org.apache.kafka.connect.runtime.rest.RestClient)
java.lang.IllegalArgumentException: Invalid URI host: null (authority: pkc-zpjg0.eu-central-1.aws.confluent.cloud%3A9092:8083)
	at org.eclipse.jetty.client.HttpClient.checkHost(HttpClient.java:521)
	at org.eclipse.jetty.client.HttpClient.newHttpRequest(HttpClient.java:506)
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:464)
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:453)
	at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:133)
	at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:115)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$reconfigureConnector$42(DistributedHerder.java:1954)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-05-12 08:34:46,626] ERROR [Worker clientId=connect-1, groupId=clickhouse-connector-sink] Request to leader to reconfigure connector tasks failed (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
org.apache.kafka.connect.runtime.rest.errors.ConnectRestException: Error trying to forward REST request: Invalid URI host: null (authority: pkc-zpjg0.eu-central-1.aws.confluent.cloud%3A9092:8083)
	at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:180)
	at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:115)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$reconfigureConnector$42(DistributedHerder.java:1954)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Invalid URI host: null (authority: pkc-zpjg0.eu-central-1.aws.confluent.cloud%3A9092:8083)
	at org.eclipse.jetty.client.HttpClient.checkHost(HttpClient.java:521)
	at org.eclipse.jetty.client.HttpClient.newHttpRequest(HttpClient.java:506)
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:464)
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:453)
	at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:133)
	... 7 more
[2023-05-12 08:34:46,626] ERROR [Worker clientId=connect-1, groupId=clickhouse-connector-sink] Failed to reconfigure connector's tasks (ClickHouseSinkConnector), retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
org.apache.kafka.connect.runtime.rest.errors.ConnectRestException: Error trying to forward REST request: Invalid URI host: null (authority: pkc-zpjg0.eu-central-1.aws.confluent.cloud%3A9092:8083)
	at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:180)
	at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:115)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$reconfigureConnector$42(DistributedHerder.java:1954)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Invalid URI host: null (authority: pkc-zpjg0.eu-central-1.aws.confluent.cloud%3A9092:8083)
	at org.eclipse.jetty.client.HttpClient.checkHost(HttpClient.java:521)
	at org.eclipse.jetty.client.HttpClient.newHttpRequest(HttpClient.java:506)
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:464)
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:453)
	at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:133)
	... 7 more
```

**Comment by danifullview** [comment]
I was able to make it work. I needed to set `CONNECT_REST_ADVERTISED_HOST_NAME`
```
  - name: CONNECT_REST_ADVERTISED_HOST_NAME
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
```
in my k8s deployment manifest.

Thank you for your help.

**Comment by danifullview** [comment]
To answer your question: `how did this happen?`
Here are a couple of things I did.
I 1st deployed on my local docker instance a connect sink pod.
I then deployed to the dev k8s cluster.
I deleted my pod, let it run on the k8s cluster, at one point I redeployed locally to test some changes.

**Comment by danifullview** [comment]
We're encountering this pretty often in our tests.
