### ISSUE TITLE
NullPointerException when destination table does not exist

### ISSUE THREAD

**Issue by creativedutchmen** [ClickHouse/clickhouse-kafka-connect#160]
### Describe the bug
When reading from a topic which does not have a sink table in clickhouse, a null pointer exception is thrown instead of a "normal" message

### Steps to reproduce
1. Set up kafka + connect + ch
2. Add a topic to the `topics` which is not a CH table

### Expected behaviour
Connector checks if the topics it's listening on have a corresponding table in CH. If not, it shows a message in the logs and continues operation for the other topics.

### Error log
```
[WARN] 2023-08-10 13:46:57,661 [task-thread-clickhouse-assets-0] com.clickhouse.kafka.connect.util.Utils handleException - Deciding how to handle exception: Cannot invoke "com.clickhouse.kafka.connect.sink.db.mapping.Table.hasDefaults()" because "table" is null
[ERROR] 2023-08-10 13:46:57,662 [task-thread-clickhouse-assets-0] org.apache.kafka.connect.runtime.WorkerSinkTask deliverMessages - WorkerSinkTask{id=clickhouse-assets-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: java.lang.NullPointerException: Cannot invoke "com.clickhouse.kafka.connect.sink.db.mapping.Table.hasDefaults()" because "table" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "com.clickhouse.kafka.connect.sink.db.mapping.Table.hasDefaults()" because "table" is null
	at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:87)
	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:143)
	at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:45)
	at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:102)
	at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
	at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:590)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:337)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:238)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:207)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:213)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:268)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "com.clickhouse.kafka.connect.sink.db.mapping.Table.hasDefaults()" because "table" is null
	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:130)
	... 16 more
```

### Configuration
clickhouse connect 0.0.18
confluent connect 7.4.1

#### ClickHouse server
clickhouse cloud

**Comment by creativedutchmen** [comment]
To add: the reason this is bad is because the connector crashes, meaning if this happens everything stops.

Since the connector supports regex for the topics, it is quite easy to accidentally create a topic that matches the regex without intending to load it into CH (so no table exists). A warning in the logs is much friendlier than having to figure out why your connector stopped working (by manually comparing matched topics with tables, note the table name is not even mentioned in the exception)
