### ISSUE TITLE
Materialized view exception can break Kafka Connect task permanently

### ISSUE THREAD

**Issue by hekike** [ClickHouse/clickhouse-kafka-connect#164]
### Describe the bug

When data is sent to a table with Materialized View, data that MV can't process will throw an exception in Connect and fail it. Connect can never recover as it cannot process the message.

### Steps to reproduce

1. Setup a materialized view
2. Send a message to Kafka with invalid data, like sending a string where Materialized View expects a number
3. Kafka Connect will break and never recover as it can't process the message

### Expected behavior

Respect `"errors.tolerance": "all"` or have a similar setting for ClickHouse Kafka Connect.

### Error log

```
023-08-23 17:36:30 [2023-08-23 15:36:30,944] WARN [clickhouse|task-0] Deciding how to handle exception: com.clickhouse.client.ClickHouseException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 , server ClickHouseNode [uri=http://clickhouse:8123/default] (com.clickhouse.kafka.connect.util.Utils:48)
2023-08-23 17:36:30 [2023-08-23 15:36:30,944] WARN [clickhouse|task-0] ClickHouseException code: 6 (com.clickhouse.kafka.connect.util.Utils:59)
2023-08-23 17:36:30 [2023-08-23 15:36:30,944] ERROR [clickhouse|task-0] Error code [6] wasn't in the acceptable list. (com.clickhouse.kafka.connect.util.Utils:74)
2023-08-23 17:36:30 [2023-08-23 15:36:30,945] ERROR [clickhouse|task-0] WorkerSinkTask{id=clickhouse-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 , server ClickHouseNode [uri=http://clickhouse:8123/default] (org.apache.kafka.connect.runtime.WorkerSinkTask:616)
2023-08-23 17:36:30 java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 , server ClickHouseNode [uri=http://clickhouse:8123/default]
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:87)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:143)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:45)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:102)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
2023-08-23 17:36:30     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2023-08-23 17:36:30     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-08-23 17:36:30     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-08-23 17:36:30     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-08-23 17:36:30     at java.base/java.lang.Thread.run(Thread.java:829)
2023-08-23 17:36:30 Caused by: java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 , server ClickHouseNode [uri=http://clickhouse:8123/default]
2023-08-23 17:36:30     at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
2023-08-23 17:36:30     at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertJson(ClickHouseWriter.java:527)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:138)
2023-08-23 17:36:30     ... 16 more
2023-08-23 17:36:30 Caused by: com.clickhouse.client.ClickHouseException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 , server ClickHouseNode [uri=http://clickhouse:8123/default]
2023-08-23 17:36:30     at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:148)
2023-08-23 17:36:30     at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:291)
2023-08-23 17:36:30     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
2023-08-23 17:36:30     ... 3 more
2023-08-23 17:36:30 Caused by: java.io.IOException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 
2023-08-23 17:36:30     at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:187)
2023-08-23 17:36:30     at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:278)
2023-08-23 17:36:30     at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:101)
2023-08-23 17:36:30     at com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:156)
2023-08-23 17:36:30     at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:289)
2023-08-23 17:36:30     ... 4 more
2023-08-23 17:36:30 [2023-08-23 15:36:30,947] ERROR [clickhouse|task-0] WorkerSinkTask{id=clickhouse-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:210)
2023-08-23 17:36:30 org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:618)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
2023-08-23 17:36:30     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2023-08-23 17:36:30     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-08-23 17:36:30     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-08-23 17:36:30     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-08-23 17:36:30     at java.base/java.lang.Thread.run(Thread.java:829)
2023-08-23 17:36:30 Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 , server ClickHouseNode [uri=http://clickhouse:8123/default]
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:87)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:143)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:45)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:102)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
2023-08-23 17:36:30     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
2023-08-23 17:36:30     ... 11 more
2023-08-23 17:36:30 Caused by: java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 , server ClickHouseNode [uri=http://clickhouse:8123/default]
2023-08-23 17:36:30     at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
2023-08-23 17:36:30     at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertJson(ClickHouseWriter.java:527)
2023-08-23 17:36:30     at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:138)
2023-08-23 17:36:30     ... 16 more
2023-08-23 17:36:30 Caused by: com.clickhouse.client.ClickHouseException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 , server ClickHouseNode [uri=http://clickhouse:8123/default]
2023-08-23 17:36:30     at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:148)
2023-08-23 17:36:30     at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:291)
2023-08-23 17:36:30     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
2023-08-23 17:36:30     ... 3 more
2023-08-23 17:36:30 Caused by: java.io.IOException: Code: 6. DB::Exception: Cannot parse string 'aa' as Float64: syntax error at begin of string. Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(JSON_VALUE(data, '$.duration_ms') :: 5, 'Float64' :: 7) -> CAST(JSON_VALUE(data, '$.duration_ms'), 'Float64') Float64 : 6': while pushing to view default.om_pmarton_local_m1 (a15975fe-3ec0-4f91-92cd-bfdbad2b5332). (CANNOT_PARSE_TEXT) (version 23.7.1.2470 (official build))
2023-08-23 17:36:30 
2023-08-23 17:36:30     at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:187)
2023-08-23 17:36:30     at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:278)
2023-08-23 17:36:30     at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:101)
2023-08-23 17:36:30     at com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:156)
2023-08-23 17:36:30     at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:289)
2023-08-23 17:36:30     ... 4 more
```

### Configuration

```json
"connector.class":                "com.clickhouse.kafka.connect.ClickHouseSinkConnector",
"database":                       c.config.SinkConfig.Database,
"errors.retry.timeout":           "30",
"hostname":                       c.config.SinkConfig.Hostname,
"port":                           fmt.Sprint(c.config.SinkConfig.Port),
"ssl":                            fmt.Sprint(c.config.SinkConfig.SSL),
"username":                       c.config.SinkConfig.Username,
"password":                       c.config.SinkConfig.Password,
"key.converter":                  "org.apache.kafka.connect.storage.StringConverter",
"value.converter":                "org.apache.kafka.connect.json.JsonConverter",
"value.converter.schemas.enable": "false",
"schemas.enable":                 "false",
"topics.regex":                   "^om_[A-Za-z0-9]+(?:_[A-Za-z0-9]+)*_events$",
"errors.tolerance":               "all",
```

#### Environment

* Kafka-Connect version: `7.4.1`
* Kafka Connect configuration:
* Kafka version: 
* Kafka environment:
* OS:

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by hekike** [comment]
@Paultagoras, this is awesome; thanks for the quick turnaround.
About analyzing the batch, to me, it looks like the Mongo Kafka Connect does something like this, [see](https://github.com/mongodb/mongo-kafka/blob/76e122b0696dc8450ede814962e1e63724f9fad2/src/main/java/com/mongodb/kafka/connect/sink/dlq/AnalyzedBatchFailedWithBulkWriteException.java#L71-L96)

It would be a great incremental feature to add later.
