### ISSUE TITLE
Enable params override for ClickHouseConfig.java from clickhouse-java

### ISSUE THREAD

**Issue by zcistkidd** [ClickHouse/clickhouse-kafka-connect#171]
**Is your feature request related to a problem? Please describe.**

In our use case for ProtoBuf + using  non-UTF8 bytes, we really need use_binary_string=true so click house would take bytes 
as a valid type for inserting into string columns. So exposing the capability of overriding configs from https://github.com/ClickHouse/clickhouse-java/blob/f2ea0e133b9f2c19416de2161019589de141fca7/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java#L351 would be a great help in many other user cases that need custom config. 

**Describe the solution you'd like**
Like what are supported from Confluent/Kafka from https://docs.confluent.io/cloud/current/connectors/bring-your-connector/custom-connector-manage.html#override-configuration-properties, there are override flag that can be used to control CH java client configs. 

**Describe alternatives you've considered**
N/A

```[tasklist]
### Tasks
```

**Comment by zcistkidd** [comment]
@Paultagoras Thx for the quick reply. I tried to add "clickhouseSettings="use_binary_string=true"", but it seems like it still failed data type and column type check here https://github.com/ClickHouse/clickhouse-kafka-connect/blob/2eea3317e7841d07b99e428c3a0d43ada39378f6/src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java#L190

**Comment by zcistkidd** [comment]
bootstrap.servers=
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
value.converter=io.confluent.connect.protobuf.ProtobufConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=true

ssl.endpoint.identification.algorithm=https
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username= password=;
request.timeout.ms=20000
retry.backoff.ms=500

producer.bootstrap.servers=
producer.ssl.endpoint.identification.algorithm=https
producer.security.protocol=SASL_SSL
producer.sasl.mechanism=PLAIN
producer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=password=;
producer.request.timeout.ms=20000
producer.retry.backoff.ms=500

consumer.bootstrap.servers=
consumer.ssl.endpoint.identification.algorithm=https
consumer.security.protocol=SASL_SSL
consumer.sasl.mechanism=PLAIN
consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username= password=
consumer.request.timeout.ms=20000
consumer.retry.backoff.ms=500

offset.flush.interval.ms=10000
offset.storage.file.filename=/tmp/connect.offsets

# Required connection configs for Confluent Cloud Schema Registry
value.converter.basic.auth.credentials.source=USER_INFO
value.converter.schema.registry.basic.auth.user.info=
value.converter.schema.registry.url=


transforms=Cast
transforms.Cast.type=org.apache.kafka.connect.transforms.Cast$Value
transforms.Cast.spec=session_id:long,src_ip_id:long,sensor_id:string


plugin.path=/usr/share/java,/Users/<username>/confluent-6.2.1/share/confluent-hub-components,/home/ubuntu/connect_plugin/

clickhouseSettings="use_binary_string=true"

**Comment by zcistkidd** [comment]
Hi @Paultagoras, sry for the late reply, was using the template above

**Comment by zcistkidd** [comment]
And the major issue is that some bytes are not UTF8 encoded, and when trying with kafka table engine, the bytes insert into string column never hit a issue

**Comment by mzitnik** [comment]
@zcistkidd We did not implement the [BYTES](https://clickhouse.com/docs/en/integrations/kafka#supported-data-types) type for Kafka Connect. Just to verify on the ClickHouse side we expect the column to be STRING?

**Comment by zcistkidd** [comment]
Hi @mzitnik , In click house java client, there is an option to set raw bytes as valid input for a string column(https://github.com/ClickHouse/clickhouse-java/blob/f2ea0e133b9f2c19416de2161019589de141fca7/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java#L351), and in click house https://clickhouse.com/docs/en/sql-reference/data-types/string, it also indicates that no encoding is required for string column . Therefore, my initial request was to exposed click house client config as overriding options in connector config

**Comment by zcistkidd** [comment]
[2023-09-20 18:45:39,173] INFO [clickhouse-sink|task-0] Inserting 500 records into topic **** (com.clickhouse.kafka.connect.sink.db.ClickHouseWriter:419)
[2023-09-20 18:45:39,182] WARN [clickhouse-sink|task-0] Deciding how to handle exception: class java.nio.HeapByteBuffer cannot be cast to class java.lang.String (java.nio.HeapByteBuffer and java.lang.String are in module java.base of loader 'bootstrap') (com.clickhouse.kafka.connect.util.Utils:50)
[2023-09-20 18:45:39,183] ERROR [clickhouse-sink|task-0] WorkerSinkTask{id=clickhouse-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: java.lang.ClassCastException: class java.nio.HeapByteBuffer cannot be cast to class java.lang.String (java.nio.HeapByteBuffer and java.lang.String are in module java.base of loader 'bootstrap') (org.apache.kafka.connect.runtime.WorkerSinkTask:616)
java.lang.RuntimeException: java.lang.ClassCastException: class java.nio.HeapByteBuffer cannot be cast to class java.lang.String (java.nio.HeapByteBuffer and java.lang.String are in module java.base of loader 'bootstrap')
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:94)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:156)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:46)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:158)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:43)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: class java.nio.HeapByteBuffer cannot be cast to class java.lang.String (java.nio.HeapByteBuffer and java.lang.String are in module java.base of loader 'bootstrap')
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWritePrimitive(ClickHouseWriter.java:323)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWriteCol(ClickHouseWriter.java:364)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:455)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:147)
        ... 16 more
[2023-09-20 18:45:39,186] ERROR [clickhouse-sink|task-0] WorkerSinkTask{id=clickhouse-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:212)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:618)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: class java.nio.HeapByteBuffer cannot be cast to class java.lang.String (java.nio.HeapByteBuffer and java.lang.String are in module java.base of loader 'bootstrap')
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:94)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:156)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:46)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:158)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:43)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        ... 11 more
Caused by: java.lang.ClassCastException: class java.nio.HeapByteBuffer cannot be cast to class java.lang.String (java.nio.HeapByteBuffer and java.lang.String are in module java.base of loader 'bootstrap')
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWritePrimitive(ClickHouseWriter.java:323)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWriteCol(ClickHouseWriter.java:364)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:455)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:147)
        ... 16 more

**Comment by zcistkidd** [comment]
I have added 
clickhouseSettings="use_binary_string=true" 
to connect config files, but it seems like some conversion issue happened

**Comment by zcistkidd** [comment]
Hi @mzitnik ，the version we are using is 0.18. I will make a minimum reproducible sample msg asap

**Comment by zcistkidd** [comment]
@Paultagoras ,Thx for the advice, I have tried with https://github.com/ClickHouse/clickhouse-kafka-connect/releases/tag/v1.0.1, but it still seems like no luck with it

**Comment by zcistkidd** [comment]
Here are the minimal reproducible eg from me 
`import argparse
from uuid import uuid4


# Protobuf generated class; resides at ./protobuf/user_pb2.py
import protobuf.na_raw_pb2 as na_raw
import protobuf.test_pb2 as test
from confluent_kafka import Producer
from confluent_kafka.serialization import StringSerializer, SerializationContext, MessageField
from confluent_kafka.schema_registry import SchemaRegistryClient
from confluent_kafka.schema_registry.protobuf import ProtobufSerializer


def delivery_report(err, msg):
    """
    Reports the failure or success of a message delivery.

    Args:
        err (KafkaError): The error that occurred on None on success.
        msg (Message): The message that was produced or failed.
    """

    if err is not None:
        print("Delivery failed for User record {}: {}".format(msg.key(), err))
        return
    print('User record {} successfully produced to {} [{}] at offset {}'.format(
        msg.key(), msg.topic(), msg.partition(), msg.offset()))


def read_ccloud_config(config_file):
    conf = {}
    with open(config_file) as fh:
        for line in fh:
            line = line.strip()
            if len(line) != 0 and line[0] != "#":
                parameter, value = line.strip().split('=', 1)
                conf[parameter] = value.strip()
    return conf

def main():
    topic = "test"

    schema_registry_conf = read_ccloud_config("schema.properties")
    schema_registry_client = SchemaRegistryClient(schema_registry_conf)

    string_serializer = StringSerializer('utf8')
    protobuf_serializer = ProtobufSerializer(test.msg,
                                             schema_registry_client,
                                             {'use.deprecated.format': False})

    producer_conf = read_ccloud_config("client.properties")

    producer = Producer(producer_conf)

    print("Producing user records to topic {}. ^C to exit.".format(topic))

    producer.poll(0.0)
    for i in range(1000):
        try:
            user = test.msg(
                id = bytes(str(uuid4()), 'utf-8')
            )
            producer.produce(topic=topic, partition=0,
                             key=string_serializer(str(uuid4())),
                             value=protobuf_serializer(user, SerializationContext(topic, MessageField.VALUE)),
                             on_delivery=delivery_report)
        except ValueError:
            print("Invalid input, discarding record...")

    print("\nFlushing records...")
    producer.flush()


if __name__ == '__main__':

    main()`

**Comment by zcistkidd** [comment]
clickhouseSettings="use_binary_string=true" has been added into bothe properties and still receiving the same issue: 
`ovider:110)
[2023-10-12 22:01:42,847] INFO [clickhouse-sink|task-0] Inserting 500 records into topic test (com.clickhouse.kafka.connect.sink.db.ClickHouseWriter:436)
[2023-10-12 22:01:42,847] ERROR [clickhouse-sink|task-0] Table column name [id] type [STRING] is not matching data column type [BYTES] (com.clickhouse.kafka.connect.sink.db.ClickHouseWriter:209)
[2023-10-12 22:01:42,847] WARN [clickhouse-sink|task-0] Deciding how to handle exception: null (com.clickhouse.kafka.connect.util.Utils:50)
[2023-10-12 22:01:42,847] ERROR [clickhouse-sink|task-0] WorkerSinkTask{id=clickhouse-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: java.lang.RuntimeException (org.apache.kafka.connect.runtime.WorkerSinkTask:616)
java.lang.RuntimeException: java.lang.RuntimeException
`

**Comment by zcistkidd** [comment]
It seems like the override config is working as exoected

**Comment by zcistkidd** [comment]
Not sure if I should post on a closed ticket, the issue I mentioned b4 was due to 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.ReflectionHelper (file:/home/ubuntu/connect_plugin/clickhouse-clickhouse-kafka-connect-v1.0.10/lib/clickhouse-kafka-connect-v1.0.10-confluent.jar) to field java.nio.ByteBuffer.hb
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release.

In normal OpenJDK env, this would throw the previous warning msg for normal JDK, but unfortunately in my prev env,  $JAVA_HOME is set to graalvm :), and due to its AOT feature, the illegal reflective access will lead to a fatal error complaining about field java.nio.ByteBuffer.hb

Hopefully, this would help someone in the future if they met the same issue
