### ISSUE TITLE
NullPointerException when a SinkRecord is missing a matching field for a mandatory column

### ISSUE THREAD

**Issue by thilo-behnke** [ClickHouse/clickhouse-kafka-connect#180]
### Describe the bug

When a SinkRecord is missing a matching field for a mandatory database table column, a NullPointerException is thrown. This causes the whole connector to fail.

### Steps to reproduce
1. Create a clickhouse table and sink data into it from a kafka topic using the clickhouse sink
2. Add a new required column to the table (`alter table xyz add column added UInt32`)
3. The ClickhouseWriter will fail in a NullPointerException when it tries to retrieve the field's metadata:

https://github.com/ClickHouse/clickhouse-kafka-connect/blob/v1.0.0/src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java#L179

```java
for (Column col : table.getColumns() ) {
            String colName = col.getName();
            Type type = col.getType();
            boolean isNullable = col.isNullable();
            if (!isNullable) { // column is not nullable, so this is true.
                Data obj = record.getJsonMap().get(colName);
                if (obj == null) { // this is true, but it does not directly create an exception!
                    validSchema = false;
                    LOGGER.error(String.format("Table column name [%s] was not found.", colName));
                }
                if (!onlyFieldsName) {
                    String colTypeName = type.name();
                    String dataTypeName = obj.getFieldType().getName().toUpperCase(); // this causes a null pointer because obj == null
                    ...
                }
            }
}
```

This causes the connector to fail, because a NullPointerException has no handling implemented: https://github.com/ClickHouse/clickhouse-kafka-connect/blob/v1.0.0/src/main/java/com/clickhouse/kafka/connect/util/Utils.java#L94

```java
        //Otherwise use Root-Cause Exception Checking

        if (rootCause instanceof SocketTimeoutException) {
            throw new RetriableException(e);
        } else if (rootCause instanceof UnknownHostException) {
            throw new RetriableException(e);
        }

        throw new RuntimeException(e);
```

### Expected behaviour

The NullPointerException should not happen, it would be better to throw a controlled exception that is handled and does not crash the connector.

The reasoning is that many tables could be fetched with one connector, so an error in one connector should not bring down the whole sink.

### Error log

```
2023-09-12 12:44:48,218] ERROR [clickhouse-sink|task-1] Table column name [added] was not found. (com.clickhouse.kafka.connect.sink.db.ClickHouseWriter:175)
[2023-09-12 12:44:48,218] WARN [clickhouse-sink|task-1] Deciding how to handle exception: null (com.clickhouse.kafka.connect.util.Utils:50)
[2023-09-12 12:44:48,219] ERROR [clickhouse-sink|task-1] WorkerSinkTask{id=clickhouse-sink-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: java.lang.NullPointerException (org.apache.kafka.connect.runtime.WorkerSinkTask:609)
java.lang.RuntimeException: java.lang.NullPointerException
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:94)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:156)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:46)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:101)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.validateDataSchema(ClickHouseWriter.java:179)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:426)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:147)
        ... 15 more
[2023-09-12 12:44:48,223] ERROR [clickhouse-sink|task-1] WorkerSinkTask{id=clickhouse-sink-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:195)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:611)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:94)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:156)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:46)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:101)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        ... 10 more
Caused by: java.lang.NullPointerException
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.validateDataSchema(ClickHouseWriter.java:179)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:426)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:147)
        ... 15 more
```

**Comment by mshustov** [comment]
> When a SinkRecord is missing a matching field for a mandatory database table column, a NullPointerException is thrown. This causes the whole connector to fail.

@Paultagoras doesn't it sound like something that should be routed to DLQ without `NullPointerException`?
