### ISSUE TITLE
Connector failed with unrecoverable exception: Write timed out after 30000 ms

### ISSUE THREAD

**Issue by oleg-savko** [ClickHouse/clickhouse-kafka-connect#244]
Connector failed and not restart when there is long heavy load on ch and kafka-connect server with following exeptions:
(connector version 1.0.1)
```
{
  "name": "...",
  "connector": {
    "state": "RUNNING",
    "worker_id": "connect:8083"
  },
  "tasks": [
    ...
    {
      "id": 1,
      "state": "FAILED",
      "worker_id": "connect:8083",
      "trace": "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
            at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:628)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:340)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:238)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:207)
            at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:229)
            at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:284)
            at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.io.IOException: Write timed out after 30000 ms
            at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:94)
            at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:173)
            at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:46)
            at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:163)
            at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:91)
            at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:593)
            ... 11 more
Caused by: java.io.IOException: Write timed out after 30000 ms
            at com.clickhouse.data.stream.NonBlockingPipedOutputStream.updateBuffer(NonBlockingPipedOutputStream.java:56)
            at com.clickhouse.data.stream.NonBlockingPipedOutputStream.updateBuffer(NonBlockingPipedOutputStream.java:41)
            at com.clickhouse.data.stream.NonBlockingPipedOutputStream.writeBytes(NonBlockingPipedOutputStream.java:193)
            at com.clickhouse.data.ClickHouseOutputStream.write(ClickHouseOutputStream.java:249)
            at com.clickhouse.data.format.BinaryStreamUtils.writeInt64(BinaryStreamUtils.java:832)
            at com.clickhouse.data.format.BinaryStreamUtils.writeFloat64(BinaryStreamUtils.java:1018)
            at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWritePrimitive(ClickHouseWriter.java:334)
            at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWriteCol(ClickHouseWriter.java:381)
            at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:472)
            at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:164)
            ... 16 more
"
    },
    ...
}
```

In ClickHouse query log thereis no insert queries with mo then 15000ms, seems mb this happend when stop the word happend on connector side or something others.

First point, seems it should try to recover this exception exception.

Second increase ClickHouse Driver Timeout not help (it always failed with default 30s) 

--------
Any suggestion how can I recover connector automatically and which props should I turn?

**Comment by ygrzjh** [comment]
Fix Handle ClickHouse JDBC Client Timeout Exception #252
