### ISSUE TITLE
With Avro Converter Bytes ClassCastException

### ISSUE THREAD

**Issue by oleg-savko** [ClickHouse/clickhouse-kafka-connect#246]
With Avro Converter Kafka Connect type bytes, not proper cast to String and throw ClassCastException:
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:628)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:340)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:238)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:207)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:229)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:284)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException
	at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:94)
	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:173)
	at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:46)
	at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:101)
	at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:91)
	at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:593)
```

**Comment by oleg-savko** [comment]
Seems fixed in https://github.com/ClickHouse/clickhouse-kafka-connect/pull/217

**Comment by oleg-savko** [comment]
https://github.com/ClickHouse/clickhouse-kafka-connect/pull/217
