### ISSUE TITLE
NullPointerException if in array type go null value with avro

### ISSUE THREAD

**Issue by oleg-savko** [ClickHouse/clickhouse-kafka-connect#278]
Use 1.0.7 version

Connector throw NullPointerException:
```
{
name: "...",
connector: {
state: "RUNNING",
worker_id: "connect:8083"
},
tasks: [
{
id: 0,
state: "FAILED",
worker_id: "connect:8083",
trace: "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:628)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:340)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:238)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:207)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:229)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:284)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:124)
	at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:68)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:593)
	... 11 more
Caused by: java.lang.NullPointerException
	at com.clickhouse.kafka.connect.sink.data.StructToJsonMap.toJsonMap(StructToJsonMap.java:67)
	at com.clickhouse.kafka.connect.sink.data.convert.SchemaRecordConvertor.convert(SchemaRecordConvertor.java:23)
	at com.clickhouse.kafka.connect.sink.data.Record.convert(Record.java:86)
	at com.clickhouse.kafka.connect.sink.ProxySinkTask.lambda$put$0(ProxySinkTask.java:86)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:87)
	at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:64)
	... 12 more
"
}
],
type: "sink"
}
```

Seems like it not handle null values correct:

message comes like:
```
{
...
  "after__agent_ids": null,
...
}
```

schema:
```
{
      "default": null,
      "name": "after__agent_ids",
      "type": [
        "null",
        {
          "items": [
            "null",
            "int"
          ],
          "type": "array"
        }
      ]
    },
```

**Comment by mlivirov** [comment]
Clickhouse seems to not allow to create a Nullable(Array(Int32)) as a field, which is making the message schema to not match to a table schema. 

https://clickhouse.com/docs/en/integrations/kafka/clickhouse-kafka-connect-sink#target-tables
