### ISSUE TITLE
Materialized views in database cause NPE on start

### ISSUE THREAD

**Issue by ysuhaas** [ClickHouse/clickhouse-kafka-connect#33]
Full stack trace:
```
2023-01-07 02:45:34,987 ERROR [###|task-1] WorkerSinkTask{id=###} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-###]
java.lang.NullPointerException
	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.start(ClickHouseWriter.java:84)
	at com.clickhouse.kafka.connect.sink.ProxySinkTask.<init>(ProxySinkTask.java:46)
	at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.start(ClickHouseSinkTask.java:54)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

From following the above stack trace, it looks like the connector attempts to execute `SHOW TABLES` and then call `DESCRIBE TABLE {database}.${tableName}` for each table in the database ([link](https://github.com/ClickHouse/clickhouse-kafka-connect/blob/main/src/main/java/com/clickhouse/kafka/connect/sink/db/helper/ClickHouseHelperClient.java#L151))

This fails because materialized views create tables with names like `.inner_id.659b0a9b-b939-4c95-9631-0d007656df21`, which is throwing an error that is uncaught. Confirmed that NPE does not occur after all materialized views are dropped from the database.

**Comment by ysuhaas** [comment]
Thanks for the quick fix team! 

We were able to test this out by building the .jar from source - indeed this fix seems to work when there are materialized views present in the table. 

There's one more error we're seeing during bootstrap that is somewhat related: 
```
2023-01-14 00:17:35,842 ERROR [clickhouse-sink.cdc.structured-trait-updates.v0|task-0] Got exception when running DESCRIBE TABLE default.pocus.cdc.structured-trait-updates.v0 (com.clickhouse.kafka.connect.sink.db.helper.ClickHouseHelperClient) [task-thread-clickhouse-sink.cdc.structured-trait-updates.v0-0]
com.clickhouse.client.ClickHouseException: Code: 62. DB::Exception: Syntax error: failed at position 44 ('-'): -trait-updates.v0. Expected one of: token, Dot. (SYNTAX_ERROR) (version 22.9.3.18 (official build))
, server ClickHouseNode [uri=http://clickhouse:8123/default]
	at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:148)
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:291)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Code: 62. DB::Exception: Syntax error: failed at position 44 ('-'): -trait-updates.v0. Expected one of: token, Dot. (SYNTAX_ERROR) (version 22.9.3.18 (official build))

	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:187)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:278)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:101)
	at com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:156)
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:289)
	... 4 more
```

It looks like the `DESCRIBE TABLE` call is not back-quoting the table name, which is causing a SQL syntax error when the table name is not strictly alphanumeric.

(Happy to move this to a new issue if needed - thanks!)

**Comment by mzitnik** [comment]
@ysuhaas can you move it to a new issue
