### ISSUE TITLE
[Guide] RedPanda

### ISSUE THREAD

**Issue by Paultagoras** [ClickHouse/clickhouse-kafka-connect#333]
We should have a detailed guide for setting up the connector with a RedPanda environment.

**Comment by jirislav** [comment]
I'm currently trying to use this connector in a [Self-Hosted Redpanda Kubernetes Setup](https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/kubernetes/k-deploy-connectors/).

I'm installing the connector by extracting [the released ZIP](https://github.com/ClickHouse/clickhouse-kafka-connect/releases/tag/v1.0.16) file within an init container that I added to the native `Deployment/redpanda-connectors`.

Using this approach, Redpanda's Connectors workload recognizes the ClickHouse Connector:

![image](https://github.com/ClickHouse/clickhouse-kafka-connect/assets/7583416/103dcc4c-1be4-42fa-b26c-10a157d671b7)

But there are problems with missing classes when trying to configure it using Avro:
```
Class io.confluent.connect.avro.AvroConverter could not be found
```

When provided [necessary JARs](https://www.confluent.io/hub/confluentinc/kafka-connect-avro-converter), I was able to instantiate the connector. But in runtime, I got:
```
org.apache.kafka.connect.errors.ConnectException: Instantiation error
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:85)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:327)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:622)
	at org.apache.kafka.connect.runtime.Worker.startSinkTask(Worker.java:525)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1800)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$32(DistributedHerder.java:1850)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: io/confluent/kafka/schemaregistry/client/SchemaRegistryClient
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:396)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:83)
	... 9 more
Caused by: java.lang.ClassNotFoundException: io.confluent.kafka.schemaregistry.client.SchemaRegistryClient
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:136)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 15 more
```

Would you consider also publishing a fat jar into releases, that would contain all the needed classes for this to work without users needing to fetch multiple modules separately?
