### ISSUE TITLE
Add logging for cases when Kafka authentication for Consumer / Producer is wrong

### ISSUE THREAD

**Issue by vladislav-bakanov** [ClickHouse/clickhouse-kafka-connect#379]
Hi! During the deployment in k8s Confluent Kafka Connect with this plugin I encountered problem with absolutely unclear logging.

**Stack:**
- My Kafka Cluster is configured with `SASL` security protocol and `SCRAM-SHA-512` method
- Kafka is 3.5.0 version

During the deployment I got an error, that is connected with connectivity to Clickhouse:
```
(org.apache.kafka.connect.runtime.distributed.DistributedHerder) [KafkaBasedLog Work Thread - kafka-connect.configs]
java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Connect to https://my-cloud-endpoint.europe-west4.gcp.clickhouse.cloud:8443 [my-cloud-endpoint.europe-west4.gcp.clickhouse.cloud/IP] failed: Read timed out, server ClickHouseNode [uri=https://my-cloud-endpoint.europe-west4.gcp.clickhouse.cloud:8443/sync_test, options={sslmode=STRICT}]@418320778
```
I thought that the problem is with connectivity to Clickhouse, but actually - problem is connected with settings of Kafka Producer and Kafka Consumer.

Connector couldn't connect to Kafka Consumer / Kafka Producer and after fix it eventually can connect to Clickhouse instance.

Can you please, add proper logging for this case. It'd save at least several days of my life...
Than you in advance ❤️

**Comment by vladislav-bakanov** [comment]
If you need any additional context/help - don't hesitate to reach out to me

**Comment by vladislav-bakanov** [comment]
@Paultagoras, I'd say, that truth is that problem is on Kafka Connect side, because it don't tell the user any information about the configuration of consumer and producer.

There are several environment variables that should be specified for the Kafka Connect:
```
- CONNECT_SECURITY_PROTOCOL
- CONNECT_SASL_JAAS_CONFIG
- CONNECT_PRODUCER_SECURITY_PROTOCOL
- CONNECT_PRODUCER_SASL_MECHANISM
- CONNECT_PRODUCER_SASL_JAAS_CONFIG
- CONNECT_COMSUMER_SECURITY_PROTOCOL
- CONNECT_CONSUMER_SASL_MECHANISM
- CONNECT_CONSUMER_SASL_JAAS_CONFIG
```

Firstly I configured only:
```
- CONNECT_SECURITY_PROTOCOL
- CONNECT_SASL_JAAS_CONFIG
- CONNECT_PRODUCER_SECURITY_PROTOCOL
```

And started to receive error message, that I mentioned above, but after specifying other connection properties (special for Consume & Producer) - it started to work properly.

By this long description of the problem I meant: "May there be an option somehow to catch wrong connection properties within the Kafka Connect setup and raise an exception in this case by the Clickhouse driver, not by Kafka Connect service"

> Do you happen to still have the logs from around that time?
Unfortunately no, logs are erased, but I can do my best to reproduce it once again, but a little bit later

**Comment by vladislav-bakanov** [comment]
@Paultagoras I faced this problem one more time.

I tried to sink data from Kafka to Clickhouse with the help of Kafka Connect + ClickHouse Driver deployed on k8s (wrapped into helm-chart).
This approach doesn't work due to connectivity issues. Log message:
```
[2024-06-03 18:51:33,190] INFO Start SinkTask:  (com.clickhouse.kafka.connect.sink.ClickHouseSinkTask)
[2024-06-03 18:51:33,190] DEBUG ClickHouseSinkConfig: hostname: my-cloud-dns.gcp.clickhouse.cloud, port: 8443, database: sandbox, username: data_user, sslEnabled: true, timeout: 30000, retry: 3, exactlyOnce: true (com.clickhouse.kafka.connect.sink.ClickHouseSinkConfig)
[2024-06-03 18:51:33,190] DEBUG ClickHouseSinkConfig: clickhouseSettings: {send_progress_in_http_headers=1, input_format_skip_unknown_fields=1, wait_end_of_query=1} (com.clickhouse.kafka.connect.sink.ClickHouseSinkConfig)
[2024-06-03 18:51:33,190] DEBUG ClickHouseSinkConfig: topicToTableMap: {uat.dwh.debezium.topic=my_table} (com.clickhouse.kafka.connect.sink.ClickHouseSinkConfig)
[2024-06-03 18:51:33,190] INFO Errant record reporter not configured. (com.clickhouse.kafka.connect.sink.ClickHouseSinkTask)
[2024-06-03 18:51:33,190] INFO Enable ExactlyOnce? true (com.clickhouse.kafka.connect.sink.ProxySinkTask)
[2024-06-03 18:51:33,190] INFO hostname: [my-cloud-dns.gcp.clickhouse.cloud] port [8443] database [sandbox] username [data_user] password [********************] sslEnabled [true] timeout [30000] (com.clickhouse.kafka.connect.sink.state.provider.KeeperStateProvider)
[2024-06-03 18:51:33,190] INFO ClickHouse URL: https://my-cloud-dns.gcp.clickhouse.cloud:8443/sandbox (com.clickhouse.kafka.connect.sink.db.helper.ClickHouseHelperClient)
[2024-06-03 18:51:33,190] DEBUG Adding username [data_user] (com.clickhouse.kafka.connect.sink.db.helper.ClickHouseHelperClient)
[2024-06-03 18:51:33,192] DEBUG Checking [com.clickhouse.client.http.ClickHouseHttpClient@27abc8ca] against [HTTP]... (com.clickhouse.client.ClickHouseNodeSelector)
[2024-06-03 18:51:33,193] DEBUG Server [ClickHouseNode [uri=https://my-cloud-dns.gcp.clickhouse.cloud:8443/sandbox, options={sslmode=STRICT}]@-1309820496] , Timeout [30000] (com.clickhouse.kafka.connect.sink.db.helper.ClickHouseHelperClient)
[2024-06-03 18:51:33,193] DEBUG Connecting to: ClickHouseNode [uri=https://my-cloud-dns.gcp.clickhouse.cloud:8443/sandbox, options={sslmode=STRICT}]@-1309820496 (com.clickhouse.client.AbstractClient)
[2024-06-03 18:51:33,193] DEBUG url [https://my-cloud-dns.gcp.clickhouse.cloud:8443/?compress=1&extremes=0] (com.clickhouse.client.http.ClickHouseHttpConnection)
[2024-06-03 18:51:33,194] DEBUG Connection established: com.clickhouse.client.http.ApacheHttpConnectionImpl@429e7c85 (com.clickhouse.client.AbstractClient)
[2024-06-03 18:51:33,194] DEBUG Query: SELECT 1 FORMAT TabSeparated (com.clickhouse.client.http.ClickHouseHttpClient)
java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Connect to https://my-cloud-dns.gcp.clickhouse.cloud:8443 [my-cloud-dns.gcp.clickhouse.cloud/35.201.102.65] failed: Read timed out, server ClickHouseNode [uri=https://my-cloud-dns.gcp.clickhouse.cloud:8443/sandbox, options={sslmode=STRICT}]@-1309820496
 at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
 at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2028)
 at com.clickhouse.client.ClickHouseClient.ping(ClickHouseClient.java:959)
 at com.clickhouse.client.AbstractClient.ping(AbstractClient.java:338)
 at com.clickhouse.client.ClickHouseClientBuilder$Agent.ping(ClickHouseClientBuilder.java:317)
 at com.clickhouse.kafka.connect.sink.db.helper.ClickHouseHelperClient.ping(ClickHouseHelperClient.java:104)
 at com.clickhouse.kafka.connect.sink.state.provider.KeeperStateProvider.<init>(KeeperStateProvider.java:49)
 at com.clickhouse.kafka.connect.sink.ProxySinkTask.<init>(ProxySinkTask.java:45)
 at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.start(ClickHouseSinkTask.java:57)
 at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:321)
 at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
 at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
 at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:829)
```

But, I did simple query with CLI inside the pod and `SELECT 1` works perfectly.

Then I just ran the same Docker image (that is used under helm deployment) with the same configuration and well - it works. It event says me different log messages, for example it notified me about the wrong types in ClickHouse table and after fix of types - it started work as I expected.

But what's wrong within the minikube deployment - I'm running out of ideas.

My Dockerfile looks like:
```
FROM confluentinc/cp-kafka-connect:7.5.4
USER root
RUN confluent-hub install --no-prompt clickhouse/clickhouse-kafka-connect:v1.0.16
USER appuser
```

My helm deployment looks like:
```
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}
  annotations:
    config-checksum: {{ include "cp-kafka-connect.configChecksum" . }}
  labels:
    {{- include "cp-kafka-connect.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cp-kafka-connect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
          {{- include "cp-kafka-connect.selectorLabels" . | nindent 8 }}
      {{- if or .Values.podAnnotations .Values.prometheus.jmx.enabled }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.prometheus.jmx.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.prometheus.jmx.port | quote }}
      {{- end }}
      {{- end }}
    spec:
      containers:
        {{- if .Values.prometheus.jmx.enabled }}
        - name: prometheus-jmx-exporter
          image: "{{ .Values.prometheus.jmx.image }}:{{ .Values.prometheus.jmx.imageTag }}"
          imagePullPolicy: "{{ .Values.prometheus.jmx.imagePullPolicy }}"
          command:
          - java
          - -XX:+UnlockExperimentalVMOptions
          - -XX:+UseCGroupMemoryLimitForHeap
          - -XX:MaxRAMFraction=1
          - -XshowSettings:vm
          - -jar
          - jmx_prometheus_httpserver.jar
          - {{ .Values.prometheus.jmx.port | quote }}
          - /etc/jmx-kafka-connect/jmx-kafka-connect-prometheus.yml
          ports:
          - containerPort: {{ .Values.prometheus.jmx.port }}
          resources:
{{ toYaml .Values.prometheus.jmx.resources | indent 12 }}
          volumeMounts:
          - name: jmx-config
            mountPath: /etc/jmx-kafka-connect
        {{- end }}
        - name: {{ template "cp-kafka-connect.name" . }}-server
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - name: kafka-connect
              containerPort: {{ .Values.servicePort}}
              protocol: TCP
            {{- if .Values.prometheus.jmx.enabled }}
            - containerPort: {{ .Values.jmx.port }}
              name: jmx
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: {{ template "cp-kafka-connect.kafka.bootstrapServers" . }}
            - name: CONNECT_GROUP_ID
              value: {{ template "cp-kafka-connect.groupId" . }}
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
              value: {{ template "cp-kafka-connect.cp-schema-registry.service-name" .}}
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              value: {{ template "cp-kafka-connect.cp-schema-registry.service-name" .}}
            - name: KAFKA_HEAP_OPTS
              value: "{{ .Values.heapOptions }}"
            # Common Kafka properties
            - name: CONNECT_SECURITY_PROTOCOL
              value: "{{ .Values.auth.kafka.security.protocol }}"
            - name: CONNECT_SASL_MECHANISM
              value: "{{ .Values.auth.kafka.sasl.mechanism }}"
            - name: CONNECT_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ template "cp-kafka-connect.fullname" . }}-secrets
                  key: sasl.jaas.config
            # Kafka producer properties
            - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
              value: "{{ .Values.auth.kafka.security.protocol }}"
            - name: CONNECT_PRODUCER_SASL_MECHANISM
              value: "{{ .Values.auth.kafka.sasl.mechanism }}"
            - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ template "cp-kafka-connect.fullname" . }}-secrets
                  key: sasl.jaas.config
            # Kafka consumer properties
            - name: CONNECT_COMSUMER_SECURITY_PROTOCOL
              value: "{{ .Values.auth.kafka.security.protocol }}"
            - name: CONNECT_CONSUMER_SASL_MECHANISM
              value: "{{ .Values.auth.kafka.sasl.mechanism }}"
            - name: CONNECT_CONSUMER_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ template "cp-kafka-connect.fullname" . }}-secrets
                  key: sasl.jaas.config
            {{- range $key, $value := .Values.configurationOverrides }}
            - name: {{ printf "CONNECT_%s" $key | replace "." "_" | upper | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.customEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            # This value deprecated, but should be specified:
            # Check this issue: https://github.com/confluentinc/cp-docker-images/issues/229
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            # This value deprecated, but should be specified:
            # Check this issue: https://github.com/confluentinc/cp-docker-images/issues/229
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            {{- if .Values.jmx.port }}
            - name: KAFKA_JMX_PORT
              value: "{{ .Values.jmx.port }}"
            {{- end }}
        {{- if .Values.customEnv.CUSTOM_SCRIPT_PATH }}
          command:
            - /bin/bash
            - -c
            - |
              /etc/confluent/docker/run &
              $CUSTOM_SCRIPT_PATH
              sleep infinity
          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | trim | indent 12 }}
          {{- end }}
        {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 10 }}
          {{- end}}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.volumes }}
{{ toYaml .Values.volumes | trim | indent 6 }}
      {{- end}}
      {{- if .Values.prometheus.jmx.enabled }}
      - name: jmx-config
        configMap:
          name: {{ template "cp-kafka-connect.fullname" . }}-jmx-configmap
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
```


Do you have any ideas what should I check within my minikube to fix this issue?

Btw I have many logs now, if you need something specific - tell me, please
