### ISSUE TITLE
Table mapping always choose the default database.

### ISSUE THREAD

**Issue by abhishekgahlot2** [ClickHouse/clickhouse-kafka-connect#387]
Hi,

I tried running it using transforms and virtual topic. Just one bug i encountered is it always expects the table to present in default database. But the data is pushed is to the database you select in the topic name.

For eg if i create a topic

bat.cat -> the data will go to database bat and  inside cat table but the table should also be present in default database too.
 
Looks like updateMapping has a bug that doesn't fetch the table from recordConvertor database and mapping isn't correctly updated.

Thats why getting errors like 

```
[Worker-069f85e6e2ddd4720] [2024-05-14 18:09:42,978] ERROR [clickhouse-20|task-3] Errors tolerance is disabled, wrapping exception: Topic: [cat], Partition: [0], MinOffset: [10], MaxOffset: [10], (QueryId: [4510c421-4b85-4282-95a7-2d309d66c9dd]) (com.clickhouse.kafka.connect.util.Utils:114)
[Worker-069f85e6e2ddd4720] Caused by: java.lang.RuntimeException: Table `cat` does not exist
[Worker-069f85e6e2ddd4720] 	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.getTable(ClickHouseWriter.java:919)
[Worker-069f85e6e2ddd4720] 	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:165)
[Worker-069f85e6e2ddd4720] 	at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:62)
[Worker-069f85e6e2ddd4720] 	... 14 more
```

I will look into this morning but thought would raise the issue anyway.

My connector config is

```
connector.class=com.clickhouse.kafka.connect.ClickHouseSinkConnector
dbTopicSplitChar=.
transforms.ExtractTopicFromKeyField.type=
tasks.max=2
topics=metrics
transforms=ExtractTopicFromKeyField
ssl=false
hostname=
database=default
port=80
enableDbTopicSplit=true
value.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
exactlyOnce=true
schemas.enable=false
transforms.ExtractTopicFromKeyField.skip.missing.or.null=true
```

**Comment by Alexandr18** [comment]
Have you tried using "topic2TableMap" in your configuration?

**Comment by abhishekgahlot2** [comment]
topic2TableMap is not relevant here, its dynamic
