### ISSUE TITLE
Expand Types of Sink Output to Match Clickhouse e.g. UInt64

### ISSUE THREAD

**Issue by PaulST2** [ClickHouse/clickhouse-kafka-connect#442]
**Is your feature request related to a problem? Please describe.**
Clickhouse supports a wide range of data types, as does Protobuf (for serdes in Kafka Schema Registry). Whilst the data types that Clickhouse-Kafka-Connect Sink supports is a much smaller subset.

Recently, using Kafka in conjunction with Schema Registry, Clickhouse-Kafka-Connect Sink, and Protobuf I attempted to write Protobuf uint64 data to a Clickhouse UInt64 table column. I discovered (from the logs) that Clickhouse-Kafka-Connect Sink converts the Protobuf uint64 to int64, attempts to write that (and fails).

I don't believe this is an intuitive expectation, and indeed a significant limitation on the usefulness of the Clickhouse-Kafka-Connect Sink.

**Describe the solution you'd like**
Please consider a much wider range of data type support to more closely match the range which Clickhouse & Protobuf supports. Most particularly, Clickhouse UInts of various widths, but indeed all types that can be matched or sensibly converted between, as available in Protobuf, and Avro.

(In this specific case I expected Protobuf uint64 to automatically convert to Clickhouse UInt64 type.)

**Describe alternatives you've considered**
CustomSMT and Custom Converters. These come with considerable complexity, however.

**Additional context**
Clickhouse-Kafka-Connect Sink - search the page for Supported Data Types:
https://clickhouse.com/docs/en/integrations/kafka/clickhouse-kafka-connect-sink

Clickhouse supported data types:
https://clickhouse.com/docs/en/sql-reference/data-types

Protobuf supported (scalar) data types:
https://protobuf.dev/programming-guides/proto3/#scalar

Avro supported data types:
https://avro.apache.org/docs/1.11.1/specification/.

**Comment by PaulST2** [comment]
Hi Paultogoras

Sure  - and thank you for looking into this.
See below:

My .proto file looks like this:

syntax = "proto3";

package ProtobufConsole.Entity;

message SimpleData {
  uint64 DataUInt64 = 1;  // Field number 1
  string DataString = 2;  // Field number 2
}

message SimpleDataArray {
  repeated SimpleData factPoints = 1;  // Field number 1
}


My data is created and sent like so:
var produce = Task.Run(async () =>
{
    Producer.Build();

    while (true)
    {
        var data1 = new SimpleData { DataUInt64 = 1, DataString = "First" };
        var data2 = new SimpleData { DataUInt64 = 2, DataString = "Second" };
        var data3 = new SimpleData { DataUInt64 = 3, DataString = "Third" };
        var dataArray = new SimpleDataArray();
        dataArray.FactPoints.Add(data1);
        dataArray.FactPoints.Add(data2);
        dataArray.FactPoints.Add(data3);

        Console.WriteLine("Sending...");
        await Producer.ProduceAsync(dataArray);
        Console.WriteLine("Sent");

        Thread.Sleep(2000);
    }
});

The above are extracted from my Visual Studio C# project which is my basic Kafka Producer

Below is a visualization of context in which this sits:

***@***.***


It succeeds up to, but fails at the Kafka Connect Sink.
I can see the unbatched element data sitting in its dedicated topic using Conduktor, and appearing with the correct schema ie:
***@***.***

(The batched topic is protobuf-topic4, whilst the unpacked single element topic is protobuf_simpleData_with_UInt64)
***@***.***

My config file for the Kafka Connector Sink is:
{
  "name": "clickhouse-sink-connector",
  "config": {
    "connector.class": "com.clickhouse.kafka.connect.ClickHouseSinkConnector",
    "tasks.max": "1",
    "hostname": "clickhouse",
    "topics": "protobuf_simpleData_with_UInt64",
    "topic2TableMap": "protobuf_simpleData_with_UInt64=SingleElementData",
    "clickhouse.url": "http://clickhouse:8123",
    "clickhouse.user": "default",
    "clickhouse.password": "",
    "clickhouse.database": "my_db",
    "clickhouse.table.autocreate": "true",
    "port":"8123",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schema.registry.url": "http://schema-registry:8081",
    "value.converter": "io.confluent.connect.protobuf.ProtobufConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8081",
    "transforms": "InsertTimestamp",
    "transforms.InsertTimestamp.type": "org.apache.kafka.connect.transforms.InsertField$Value",
    "transforms.InsertTimestamp.timestamp.field": "timestamp"
  }
}


My Cilckhouse table description:
DESCRIBE TABLE SingleElementData

Query id: 22f71c8d-e010-46b4-b2d2-0b1825f78f0a

┌─name───────┬─type─────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ DataUInt64 │ UInt64   │              │                    │         │                  │                │
│ DataString │ String   │              │                    │         │                  │                │
│ timestamp  │ DateTime │              │                    │         │                  │                │
└────────────┴──────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

3 rows in set. Elapsed: 0.005 sec.


When I curl POST the config file to the Kafka Connector Sink:
curl -X POST -H "Content-Type: application/json" --data @clickhouse-sink-connector-protobuf.json http://localhost:8083/connectors
{"name":"clickhouse-sink-connector","config":{"connector.class":"com.clickhouse.kafka.connect.ClickHouseSinkConnector","tasks.max":"1","hostname":"clickhouse","topics":"protobuf_simpleData_with_UInt64","topic2TableMap":"protobuf_simpleData_with_UInt64=SingleElementData","clickhouse.url":http://clickhouse:8123,"clickhouse.user":"default","clickhouse.password":"","clickhouse.database":"my_db","clickhouse.table.autocreate":"true","port":"8123","key.converter":"org.apache.kafka.connect.json.JsonConverter","key.converter.schema.registry.url":http://schema-registry:8081,"value.converter":"io.confluent.connect.protobuf.ProtobufConverter","value.converter.schema.registry.url":http://schema-registry:8081,"transforms":"InsertTimestamp","transforms.InsertTimestamp.type":"org.apache.kafka.connect.transforms.InsertField$Value","transforms.InsertTimestamp.timestamp.field":"timestamp","name":"clickhouse-sink-connector"},"tasks":[],"type":"sink"}

When I then enter the container and check the logs I see this:
[2024-09-23 22:04:11,473] ERROR Table column name [DataUInt64] type [UINT64] is not matching data column type [INT64] (com.clickhouse.kafka.connect.sink.db.ClickHouseWriter)
[2024-09-23 22:04:11,480] ERROR Errors tolerance is disabled, wrapping exception: Topic: [protobuf_simpleData_with_UInt64], Partition: [0], MinOffset: [0], MaxOffset: [499], (QueryId: [fd32050b-6fda-4bc6-976f-bbee836bff1c]) (com.clickhouse.kafka.connect.util.Utils)
[2024-09-23 22:04:11,483] ERROR WorkerSinkTask{id=clickhouse-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Number of records: 500 (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.RuntimeException: Number of records: 500
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:126)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:68)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Topic: [protobuf_simpleData_with_UInt64], Partition: [0], MinOffset: [0], MaxOffset: [499], (QueryId: [fd32050b-6fda-4bc6-976f-bbee836bff1c])
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:68)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:133)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:99)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:64)
        ... 11 more
Caused by: java.lang.RuntimeException: Data schema validation failed.
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinaryV1(ClickHouseWriter.java:743)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:676)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:196)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:66)
        ... 14 more
[2024-09-23 22:04:11,489] ERROR WorkerSinkTask{id=clickhouse-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:611)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Number of records: 500
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:126)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:68)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        ... 10 more
Caused by: java.lang.RuntimeException: Topic: [protobuf_simpleData_with_UInt64], Partition: [0], MinOffset: [0], MaxOffset: [499], (QueryId: [fd32050b-6fda-4bc6-976f-bbee836bff1c])
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:68)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:133)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:99)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:64)
        ... 11 more
Caused by: java.lang.RuntimeException: Data schema validation failed.
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinaryV1(ClickHouseWriter.java:743)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:676)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:196)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:66)
        ... 14 more


Please let me know if there is anything further you need.

Thank you

Regards

Paul Duncan

**Comment by PaulST2** [comment]
Hi Paultogoras

Sure  - and thank you for looking into this.
See below:

My .proto file looks like this:

```
syntax = "proto3";

package ProtobufConsole.Entity;

message SimpleData {
  uint64 DataUInt64 = 1;  // Field number 1
  string DataString = 2;  // Field number 2
}

message SimpleDataArray {
  repeated SimpleData factPoints = 1;  // Field number 1
}
```


My data is created and sent like so:
```
var produce = Task.Run(async () =>
{
    Producer.Build();

    while (true)
    {
        var data1 = new SimpleData { DataUInt64 = 1, DataString = "First" };
        var data2 = new SimpleData { DataUInt64 = 2, DataString = "Second" };
        var data3 = new SimpleData { DataUInt64 = 3, DataString = "Third" };
        var dataArray = new SimpleDataArray();
        dataArray.FactPoints.Add(data1);
        dataArray.FactPoints.Add(data2);
        dataArray.FactPoints.Add(data3);

        Console.WriteLine("Sending...");
        await Producer.ProduceAsync(dataArray);
        Console.WriteLine("Sent");

        Thread.Sleep(2000);
    }
});
```

The above are extracted from my Visual Studio C# project which is my basic Kafka Producer
Below is a visualization of context in which this sits:

![Screenshot 2024-09-24 104803](https://github.com/user-attachments/assets/28e556f5-2ab6-479a-9066-c6efb5a2cf56)


It succeeds up to, but fails at the Kafka Connect Sink. 
I can see the unbatched element data sitting in its dedicated topic using Conduktor, and appearing with the correct schema ie:
 

(The batched topic is protobuf-topic4, whilst the unpacked single element topic is protobuf_simpleData_with_UInt64)
 
My config file for the Kafka Connector Sink is:
```
({
  "name": "clickhouse-sink-connector",
  "config": {
    "connector.class": "com.clickhouse.kafka.connect.ClickHouseSinkConnector",
    "tasks.max": "1",
    "hostname": "clickhouse",
    "topics": "protobuf_simpleData_with_UInt64",
    "topic2TableMap": "protobuf_simpleData_with_UInt64=SingleElementData",
    "clickhouse.url": "http://clickhouse:8123/",
    "clickhouse.user": "default",
    "clickhouse.password": "",
    "clickhouse.database": "my_db",
    "clickhouse.table.autocreate": "true",
    "port":"8123",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schema.registry.url": "http://schema-registry:8081/",
    "value.converter": "io.confluent.connect.protobuf.ProtobufConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8081/",
    "transforms": "InsertTimestamp",
    "transforms.InsertTimestamp.type": "org.apache.kafka.connect.transforms.InsertField$Value",
    "transforms.InsertTimestamp.timestamp.field": "timestamp"
  }
})
```


My Cilckhouse table description:
DESCRIBE TABLE SingleElementData

Query id: 22f71c8d-e010-46b4-b2d2-0b1825f78f0a

┌─name───────┬─type─────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ DataUInt64 │ UInt64   │              │                    │         │                  │                │
│ DataString │ String   │              │                    │         │                  │                │
│ timestamp  │ DateTime │              │                    │         │                  │                │
└────────────┴──────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

3 rows in set. Elapsed: 0.005 sec.


When I curl POST the config file to the Kafka Connector Sink:
`curl -X POST -H "Content-Type: application/json" --data @clickhouse-sink-connector-protobuf.json `http://localhost:8083/connectors
{"name":"clickhouse-sink-connector","config":{"connector.class":"com.clickhouse.kafka.connect.ClickHouseSinkConnector","tasks.max":"1","hostname":"clickhouse","topics":"protobuf_simpleData_with_UInt64","topic2TableMap":"protobuf_simpleData_with_UInt64=SingleElementData","clickhouse.url":http://clickhouse:8123/,"clickhouse.user":"default","clickhouse.password":"","clickhouse.database":"my_db","clickhouse.table.autocreate":"true","port":"8123","key.converter":"org.apache.kafka.connect.json.JsonConverter","key.converter.schema.registry.url":http://schema-registry:8081/,"value.converter":"io.confluent.connect.protobuf.ProtobufConverter","value.converter.schema.registry.url":http://schema-registry:8081/,"transforms":"InsertTimestamp","transforms.InsertTimestamp.type":"org.apache.kafka.connect.transforms.InsertField$Value","transforms.InsertTimestamp.timestamp.field":"timestamp","name":"clickhouse-sink-connector"},"tasks":[],"type":"sink"}

When I then enter the container and check the logs I see this:
[2024-09-23 22:04:11,473] ERROR Table column name [DataUInt64] type [UINT64] is not matching data column type [INT64] (com.clickhouse.kafka.connect.sink.db.ClickHouseWriter)
[2024-09-23 22:04:11,480] ERROR Errors tolerance is disabled, wrapping exception: Topic: [protobuf_simpleData_with_UInt64], Partition: [0], MinOffset: [0], MaxOffset: [499], (QueryId: [fd32050b-6fda-4bc6-976f-bbee836bff1c]) (com.clickhouse.kafka.connect.util.Utils)
[2024-09-23 22:04:11,483] ERROR WorkerSinkTask{id=clickhouse-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Number of records: 500 (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.RuntimeException: Number of records: 500
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:126)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:68)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Topic: [protobuf_simpleData_with_UInt64], Partition: [0], MinOffset: [0], MaxOffset: [499], (QueryId: [fd32050b-6fda-4bc6-976f-bbee836bff1c])
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:68)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:133)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:99)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:64)
        ... 11 more
Caused by: java.lang.RuntimeException: Data schema validation failed.
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinaryV1(ClickHouseWriter.java:743)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:676)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:196)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:66)
        ... 14 more
[2024-09-23 22:04:11,489] ERROR WorkerSinkTask{id=clickhouse-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:611)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Number of records: 500
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:126)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:68)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        ... 10 more
Caused by: java.lang.RuntimeException: Topic: [protobuf_simpleData_with_UInt64], Partition: [0], MinOffset: [0], MaxOffset: [499], (QueryId: [fd32050b-6fda-4bc6-976f-bbee836bff1c])
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:68)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:133)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:99)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:64)
        ... 11 more
Caused by: java.lang.RuntimeException: Data schema validation failed.
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinaryV1(ClickHouseWriter.java:743)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:676)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:196)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:66)
        ... 14 more


Please let me know if there is anything further you need.

Thank you

**Comment by PaulST2** [comment]
I should mention also, the Clickhouse Docker image I'm using: 
clickhouse/clickhouse-server:23.3

**Comment by PaulST2** [comment]
Hi Paultogoras

Yes it has worked. I am now getting Protobuf uint64 data across to a Clickhouse Uint64 column via Kafka Connect + Clickhouse-Kafka-Connect v 1.2.3

Thank you!

**Comment by PaulST2** [comment]
Hi again Paultagoras

Sorry to report, using Clickhouse-Kafka-Connect v 1.2.3 the issue would seem to exist also with respect to protobuf type uint32 -> Clickhouse column type UInt32.

I'll post logs shortly. (Very similar to the logs posted earlier).

**Comment by PaulST2** [comment]
Logs showing equivalent error for uint32 (as for prior issue, now solved with uint64):

`[2024-10-02 02:21:21,183] ERROR Table column name [DataUInt32] type [UINT32] is not matching data column type [INT64] (com.clickhouse.kafka.connect.sink.db.ClickHouseWriter)
[2024-10-02 02:21:21,185] ERROR Errors tolerance is disabled, wrapping exception: Topic: [protobuf_simpleData_with_UInt64_12], Partition: [0], MinOffset: [0], MaxOffset: [11], (QueryId: [966d93bb-4ac1-4bf5-8e9b-233ff4cc3a79]) (com.clickhouse.kafka.connect.util.Utils)
[2024-10-02 02:21:21,186] ERROR WorkerSinkTask{id=clickhouse-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Number of records: 12 (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.RuntimeException: Number of records: 12
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:126)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:71)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Topic: [protobuf_simpleData_with_UInt64_12], Partition: [0], MinOffset: [0], MaxOffset: [11], (QueryId: [966d93bb-4ac1-4bf5-8e9b-233ff4cc3a79])
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:62)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:127)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:99)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:65)
        ... 11 more
Caused by: java.lang.RuntimeException: Data schema validation failed.
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinaryV1(ClickHouseWriter.java:755)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:688)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:196)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:60)
        ... 14 more
[2024-10-02 02:21:21,193] ERROR WorkerSinkTask{id=clickhouse-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:611)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Number of records: 12
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:126)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:71)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        ... 10 more
Caused by: java.lang.RuntimeException: Topic: [protobuf_simpleData_with_UInt64_12], Partition: [0], MinOffset: [0], MaxOffset: [11], (QueryId: [966d93bb-4ac1-4bf5-8e9b-233ff4cc3a79])
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:62)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:127)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:99)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:65)
        ... 11 more
Caused by: java.lang.RuntimeException: Data schema validation failed.
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinaryV1(ClickHouseWriter.java:755)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:688)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:196)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:60)
        ... 14 more
`

**Comment by bichselb** [comment]
I encountered the same problem with `uint32`.

More fundamentally, I agree with the request to expand the supported types. In my case, I would benefit from support for `uint128`, `int128`, `IPv4`, `IPv6`,  `Nullable`, and `DateTime64` (seems to support reading `uint64` via protobuf, but not [Timestamp](https://protobuf.dev/reference/php/api-docs/Google/Protobuf/Timestamp.html)).
