### ISSUE TITLE
Avro date logical type causes ClassCastException in ClickHouse Sink Connector

### ISSUE THREAD

**Issue by joseandro** [ClickHouse/clickhouse-kafka-connect#478]
### Describe the bug
I am encountering a ClassCastException when using the ClickHouse Kafka Connect sink to process Avro data containing the date logical type. Avro represents the date logical type as an integer (number of days since the Unix epoch). The exception seems to occur because the connector attempts to cast an integer to a Byte, which leads to the error.

```
java.lang.RuntimeException: Topic: [topicName], Partition: [13], MinOffset: [0], MaxOffset: [304], (QueryId: [d12bc47f-1ed6-4e5d-b787-cdd70fa819e6])
    at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:59)
    ...
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Byte (java.lang.Integer and java.lang.Byte are in module java.base of loader 'bootstrap')
    at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWritePrimitive(ClickHouseWriter.java:584)
    at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWriteColValue(ClickHouseWriter.java:410)
    at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWriteCol(ClickHouseWriter.java:668)
    at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinaryV1(ClickHouseWriter.java:781)
    at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:690)
    at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:204)
    ...
```

### Steps to reproduce
1. Use Avro to define a schema with a date logical type.
Example:
```
{
  "type": "record",
  "name": "ARecord",
  "fields": [
    { "name": "id", "type": "string" },
    { "name": "referenceDate", "type": { "type": "int", "logicalType": "date" } }
  ]
}
```
2. Produce messages to a Kafka topic using the schema above.
3. Configure the ClickHouse Kafka Connect Sink to consume messages from the topic.
4. Observe the error in the connector logs or DLQ.

### Expected behaviour
The connector should correctly handle the Avro date logical type and insert the data into ClickHouse without errors.

### Actual Behavior
The connector throws a ClassCastException, indicating it attempts to cast an Integer (Avro date representation) to a Byte. No data is being stored in ClickHouse as it is all being sent to the DLQ.

#### Environment
* Kafka-Connect version: 7.7.1
* Kafka Connect configuration: 
```
    "connector.class": "com.clickhouse.kafka.connect.ClickHouseSinkConnector",
    "hostname": "'$CH_HTTP_HOSTNAME'",
    "port": "'$CH_HTTP_PORT'",
    "username": "<USERNAME>",
    "password": "**********",
    "database": "<DB_NAME>",
    "exactlyOnce": "true",
    "ssl": "false",
    "tasks.max": "1",
    "topics": "<TOPIC_NAME>",
    "topic2TableMap": "<TOPIC_NAME>=<TABLE_NAME>",
    "key.converter": "'$CONNECT_KEY_CONVERTER'",
    "value.converter": "'$CONNECT_VALUE_CONVERTER'",
    "value.converter.schema.registry.url": "'$CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL'",
    "value.converter.schemas.enable": "true",
    "errors.tolerance": "all",
    "errors.retry.timeout": "60",
    "errors.deadletterqueue.topic.name": "<DLQ_NAME>",
    "errors.deadletterqueue.context.headers.enable": "true",
    "errors.deadletterqueue.topic.replication.factor": "1"
```
* Kafka version: 7.7.1
* Schema registry: 7.7.1
* OS: docker image running on a m1 macOS
* Avro schema: 
```
{
  "type": "record",
  "name": "ARecord",
   "fields": [
    { "name": "symb", "type": "string" },
    { "name": "name", "type": "string" },
    {
      "name": "strike",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 10,
        "scale": 2
      }
    },
    {
      "name": "maturity",
      "type": { "type": "int", "logicalType": "date" }
    },
    { "name": "size", "type": ["null", "int"], "default": null },
    { "name": "putOrCall", "type": "int" },
    {
      "name": "tTime",
      "type": { "type": "long", "logicalType": "timestamp-millis" }
    }
  ]
}
```

#### ClickHouse server
* ClickHouse Server version: 24.10
* ClickHouse Keeper version: 24.10-alpine
* `CREATE TABLE` statements for tables involved:
```
CREATE TABLE IF NOT EXISTS db_name.table_name (
    symb String,
    name String,
    strike Decimal64(2),
    maturity Date32,
    size Nullable(UInt32),
    putOrCall UInt8,
    tTime DateTime64(3, 'UTC')
) ENGINE = MergeTree ORDER BY (tTime, symb);
```
* Sample data for all these tables: no data is getting stored in tables because it is all going to the DLQ topic.

### Additional Context
It appears the date logical type, represented as an integer in Avro, is not being correctly handled in the connector code. The connector should either automatically map it to a Date/Int32 in ClickHouse or allow explicit configuration to handle such types.

**Comment by joseandro** [comment]
Closing this as invalid. The error was coming from other types that were being incorrectly handled (putOrCall and size). Changing them to Int32 fixed the problem.
