### ISSUE TITLE
If a UUID with an empty string is encountered at the input, an exception is thrown

### ISSUE THREAD

**Issue by DmitryTuryshev** [ClickHouse/clickhouse-kafka-connect#479]
https://github.com/ClickHouse/clickhouse-kafka-connect/blob/fef6bb714d2cca61bead75f16dd9c09ea215b9c5/src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java#L611

`WorkerSinkTask{id=clickhouse_sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Number of records: 1000 (org.apache.kafka.connect.runtime.WorkerSinkTask:633)
Nov 26 10:46:58 debezium-analytics sh[1049526]: java.lang.RuntimeException: Number of records: 1000
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:126)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:71)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at java.base/java.lang.Thread.run(Thread.java:840)
Nov 26 10:46:58 debezium-analytics sh[1049526]: Caused by: java.lang.RuntimeException: Topic: [zoom_trigger_trigger_users], Partition: [0], MinOffset: [58743], MaxOffset: [58745], (QueryId: [09f9eb7a-ca41-490f-bc2c-14b0fc7538b2])
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:62)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:196)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:99)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:65)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         ... 12 more
Nov 26 10:46:58 debezium-analytics sh[1049526]: Caused by: java.lang.IllegalArgumentException: Invalid UUID string:
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at java.base/java.util.UUID.fromString1(UUID.java:280)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at java.base/java.util.UUID.fromString(UUID.java:258)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWritePrimitive(ClickHouseWriter.java:605)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWriteColValue(ClickHouseWriter.java:403)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWriteCol(ClickHouseWriter.java:661)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinaryV1(ClickHouseWriter.java:774)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:683)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:197)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:60)
Nov 26 10:46:58 debezium-analytics sh[1049526]:         ... 15 more`

Example record here trigger_id_uuid is empty, but not null :
`{"trigger_id_uuid":"", "more_":"...", "id":"123",
__deleted":{"string":"true"},
"__ts_ms":{"long":111111111},
"__op":{"string":"d"}}`

**Comment by DmitryTuryshev** [comment]
```
"name": "trigger_id",
"type": {
  "type": "string",
  "connect.version": 1,
  "connect.name": "io.debezium.data.Uuid"
}
```
@Paultagoras Hi, there! Thx for your question! 
source db postgres has table schema :
```
....
trigger_id uuid NOT NULL
....
```

Also, there is a delete event for this record. It means just "" getting by debezium

**Comment by DmitryTuryshev** [comment]
NP, the field is in the destination table.
``trigger_id` Nullable(UUID) CODEC(ZSTD(1)) `

Also, I'm sure this problem is not in the destination table, because there is an error with decoding "" to UUID
