### ISSUE TITLE
DB::Exception: KeeperMap is disabled because 'keeper_map_path_prefix' config is not defined. (BAD_ARGUMENTS)

### ISSUE THREAD

**Issue by ibakhsh** [ClickHouse/clickhouse-kafka-connect#56]
Hi 
I have install kafka connect (https://github.com/ClickHouse/clickhouse-kafka-connect/releases/download/v0.0.8-beta/clickhouse-kafka-connect-0.0.8.zip)

and configured my (connect-sink.properties) file as following: 
```
name = kafka-sink
connector.class=com.clickhouse.kafka.connect.ClickHouseSinkConnector
bootstrap.servers=localhost:9092
key.converter.schemas.enable=true
value.converter.schemas.enable=true
offset.storage.file.filename=/tmp/connect.sink
rest.port=10082
rest.host.name=localhost
rest.advertised.port=10082
rest.advertised.host.name=localhost

key.converter=org.apache.kafka.connect.storage.StringConverter

tasks.max=1
topics=mysql1.myDB.test
#ssl=true
#security.protocol=SSL
hostname=localhost
database=myDB
username=default
password=P#ssw0rd
#ssl.truststore.location=/tmp/kafka.client.truststore.jks
port=8123
value.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
exactlyOnce=true
schemas.enable=false
```

when I try to start the kafka standalone to sink kafka into clickhouse I get this error: 

```
[2023-02-13 08:10:57,267] WARN [kafka-sink|task-0] Query retry 1 out of 3 (com.clickhouse.kafka.connect.sink.db.helper.ClickHouseHelperClient:101)
com.clickhouse.client.ClickHouseException: Code: 36. DB::Exception: KeeperMap is disabled because 'keeper_map_path_prefix' config is not defined. (BAD_ARGUMENTS) (version 23.1.3.5 (official build))
, server ClickHouseNode [uri=http://localhost:8123/myDB]
        at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:148)
        at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:291)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Code: 36. DB::Exception: KeeperMap is disabled because 'keeper_map_path_prefix' config is not defined. (BAD_ARGUMENTS) (version 23.1.3.5 (official build))

        at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:187)
        at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:278)
        at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:101)
        at com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:156)
        at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:289)
        ... 4 more
```

any idea what I need to do to fix this issue ?

**Comment by mshustov** [comment]
@ibakhsh, what ClickHouse version do you use?

**Comment by mzitnik** [comment]
@ibakhsh, if you are using ClickHouse Cloud, it is already enabled.
If you are using local instance please follow this like https://clickhouse.com/docs/en/engines/table-engines/special/keeper-map/
