### ISSUE TITLE
Caused by: java.net.SocketException: Unexpected end of file from server

### ISSUE THREAD

**Issue by mtgnoah** [ClickHouse/clickhouse-kafka-connect#86]
### Describe the bug
This error happened hours after I had started this process with no other visible issues. This causes a crash afterwards. I am using these settings:

```connector.class=com.clickhouse.kafka.connect.ClickHouseSinkConnector
tasks.max=4
topics=ethereum_blocks,ethereum_logs,ethereum_transactions,ethereum_traces
ssl=false
hostname=
database=ethereum
password=
port=8123
value.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
exactlyOnce=false
username=
schemas.enable=false
```
### Steps to reproduce
1. Start kafka connect with the clickhouse connector and wait a few hours

#### Environment
* Kafka-Connect version:
* Kafka Connect configuration:
* Kafka version:
* Kafka environment:
* OS:

#### ClickHouse server
ClickHouse server version 23.3.1 revision 54462

```sql
CREATE TABLE ethereum.ethereum_traces
(
    type LowCardinality(String),
    transaction_index UInt16,
    from_address String,
    to_address String,
    value Decimal(38, 0),
    input String,
    output String,
    trace_type Enum8('call' = 1, 'create' = 2, 'suicide' = 3, 'reward' = 4, 'genesis' = 5, 'daofork' = 6),
    call_type Enum8('' = 0, 'call' = 1, 'callcode' = 2, 'delegatecall' = 3, 'staticcall' = 4),
    reward_type Enum8('' = 0, 'block' = 1, 'uncle' = 2),
    gas UInt32 CODEC(Delta(4), ZSTD(1)),
    gas_used UInt32,
    subtraces UInt32,
    trace_address Array(UInt32),
    error String,
    status Bool,
    transaction_hash String,
    block_number UInt64,
    trace_id String,
    trace_index UInt16,
    block_timestamp UInt64,
    block_hash String,
    item_id String,
    item_timestamp String,
    chain_id UInt32
)
ENGINE = MergeTree
ORDER BY (trace_type, block_number, block_timestamp)
TTL now() + INTERVAL 1 DAY

```

**Comment by abdelhakimbendjabeur** [comment]
Did it sink some data?

I don't think the support for LowCardinality type is working properly, you can try without it and see what happens

**Comment by mtgnoah** [comment]
I actually figured out it was a materialized view that was causing performance issues that impacted this process too because it slowed down reads

**Comment by mtgnoah** [comment]
Actually that wasn't it because I just rechecked and it broke again

**Comment by mtgnoah** [comment]
It does sink some data but it breaks after a few hours of running

**Comment by mtgnoah** [comment]
I tried it without it and it still gives the same exception.

**Comment by mzitnik** [comment]
@mtgnoah So, I guess you are working with an on-prem instance of ClickHouse.
Please provide if you can 
- ClickHouse sink logging?
- Can you send the data that was sent just before the problem happened (you can find it by looking at the offsets that were sent and pulling it from Kafka)
- if it is a dataset that you can send us (we can check it)

**Comment by mtgnoah** [comment]
Ok here is the data from this error: 
```
[2023-04-18 18:27:25,308] INFO doLogic Topic [ethereum_traces] Partition [3] offset [75178762:75178764] (com.clickhouse.kafka.connect.si
nk.processing.Processing:88)
[2023-04-18 18:27:25,308] INFO Number of records to insert 3 to table name ethereum_traces (com.clickhouse.kafka.connect.sink.db.ClickHo
useWriter:419) 
java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Unexpected end of file from server, server ClickHous
eNode
```

The data from that topic, partition, and offset for 3 records same as sent to clickhouse:
```
null-{"type": "trace", "transaction_index": 0, "from_address": "0x7e5c0a5029e5979f565043a6bcd2eaf19f447858", "to_address": "0xef1c6e6770
3c7bd7107eed8303fbe6ec2554bf6b", "value": 0, "input": "0x3593564c00000000000000000000000000000000000000000000000000000000000000600000000
0000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000643ee7ef000000000000000
00000000000000000000000000000000000000000000000030a090c000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000
0000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000
00000000000000000000001600000000000000000000000008963c85dc6cb4d3e9295da8c4b2a97330c9a3982000000000000000000000000fffffffffffffffffffffff
fffffffffffffffff0000000000000000000000000000000000000000000000000000000064666c090000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000ef1c6e67703c7bd7107eed8303fbe6ec2554bf6b00000000000000000000000000000000000000000000000000000000643ee61
100000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000418130e31
3537c1df43e48643325479c2cb9bbb701c84ca6a08c367e1c0e2983256798134e78e96a81ddccda48dbf7f86557ab7cf3248c70488c1c403cf95bf6451b0000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000
0000000000000000000000000000000000000000200000000000000000000000000000000000000000000000001aa535d3d0c00000000000000000000000000000000000
00000000000000000000023fb109ceae900000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000
000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000008963c85dc6cb4d3e9295da8
c4b2a97330c9a3982000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000000000
000000040000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000001aa535d3d0c000
0", "output": "0x", "trace_type": "call", "call_type": "call", "reward_type": null, "gas": 214823, "gas_used": 182595, "subtraces": 9, "
trace_address": [], "error": null, "status": 1, "transaction_hash": "0x8965401330d63b1d506bd7ec279ef5a273c4d1123e4361e197c291cd65937584"
, "block_number": 17075322, "trace_id": "call_0x8965401330d63b1d506bd7ec279ef5a273c4d1123e4361e197c291cd65937584_", "trace_index": 0, "b
lock_timestamp": 1681842443, "block_hash": "0xa0cca961d55bf02ff9f5f2dcfb99903ee88981755050e4fe6510402472e634d7", "item_id": "trace_call_
0x8965401330d63b1d506bd7ec279ef5a273c4d1123e4361e197c291cd65937584_", "item_timestamp": "2023-04-18T18:27:23Z", "chain_id": 1}
null-{"type": "trace", "transaction_index": 0, "from_address": "0xef1c6e67703c7bd7107eed8303fbe6ec2554bf6b", "to_address": "0xd56d3c7a80
ffff89f14afa2ac062a3346a2820f7", "value": 0, "input": "0x0902f1ac", "output": "0x000000000000000000000000000000000000000000000000000f400
d258bc083000000000000000000000000000000000000000000000000c585f42a5bdf453800000000000000000000000000000000000000000000000000000000643ee0f
f", "trace_type": "call", "call_type": "staticcall", "reward_type": null, "gas": 164441, "gas_used": 2504, "subtraces": 0, "trace_addres
s": [1], "error": null, "status": 1, "transaction_hash": "0x8965401330d63b1d506bd7ec279ef5a273c4d1123e4361e197c291cd65937584", "block_nu
mber": 17075322, "trace_id": "call_0x8965401330d63b1d506bd7ec279ef5a273c4d1123e4361e197c291cd65937584_1", "trace_index": 2, "block_times
tamp": 1681842443, "block_hash": "0xa0cca961d55bf02ff9f5f2dcfb99903ee88981755050e4fe6510402472e634d7", "item_id": "trace_call_0x89654013
30d63b1d506bd7ec279ef5a273c4d1123e4361e197c291cd65937584_1", "item_timestamp": "2023-04-18T18:27:23Z", "chain_id": 1}
null-{"type": "trace", "transaction_index": 0, "from_address": "0xef1c6e67703c7bd7107eed8303fbe6ec2554bf6b", "to_address": "0x0000000000
22d473030f116ddee9f6b43ac78ba3", "value": 0, "input": "0x36c785160000000000000000000000007e5c0a5029e5979f565043a6bcd2eaf19f4478580000000
00000000000000000d56d3c7a80ffff89f14afa2ac062a3346a2820f70000000000000000000000000000000000000000000000000000214b8d9c2d4f000000000000000
0000000008963c85dc6cb4d3e9295da8c4b2a97330c9a3982", "output": "0x", "trace_type": "call", "call_type": "call", "reward_type": null, "gas
": 160408, "gas_used": 42000, "subtraces": 1, "trace_address": [2], "error": null, "status": 1, "transaction_hash": "0x8965401330d63b1d5
06bd7ec279ef5a273c4d1123e4361e197c291cd65937584", "block_number": 17075322, "trace_id": "call_0x8965401330d63b1d506bd7ec279ef5a273c4d112
3e4361e197c291cd65937584_2", "trace_index": 3, "block_timestamp": 1681842443, "block_hash": "0xa0cca961d55bf02ff9f5f2dcfb99903ee88981755
050e4fe6510402472e634d7", "item_id": "trace_call_0x8965401330d63b1d506bd7ec279ef5a273c4d1123e4361e197c291cd65937584_2", "item_timestamp"
: "2023-04-18T18:27:23Z", "chain_id": 1}
```

Here is the updated table. I made some changes adding Nullable Columns because I realized a few of the values were actually nullable. 

```
CREATE TABLE ethereum.ethereum_traces
(
    `type` String,
    `transaction_index` UInt16,
    `from_address` String,
    `to_address` String,
    `value` Decimal(38, 0),
    `input` String,
    `output` String,
    `trace_type` Enum8('call' = 1, 'create' = 2, 'suicide' = 3, 'reward' = 4, 'genesis' = 5, 'daofork' = 6),
    `call_type` Enum8('' = 0, 'call' = 1, 'callcode' = 2, 'delegatecall' = 3, 'staticcall' = 4),
    `reward_type` Nullable(Enum8('' = 0, 'block' = 1, 'uncle' = 2)),
    `gas` UInt32 CODEC(Delta(4), ZSTD(1)),
    `gas_used` UInt32,
    `subtraces` UInt32,
    `trace_address` Array(UInt32),
    `error` Nullable(String),
    `status` Bool,
    `transaction_hash` String,
    `block_number` UInt64,
    `trace_id` String,
    `trace_index` UInt16,
    `block_timestamp` UInt64,
    `block_hash` String,
    `item_id` String,
    `item_timestamp` String,
    `chain_id` UInt32,
    `selector` Nullable(String) MATERIALIZED substring(input, 1, 10)
)
ENGINE = ReplacingMergeTree
ORDER BY item_id
SETTINGS index_granularity = 8192
```

**Comment by mtgnoah** [comment]
@mzitnik It's just such a weird issue because it crashes at a different point every time so it's hard for me to pinpoint exactly where it is having issues. At this point I am debating on just making most of the columns nullable to fix issues.

**Comment by mzitnik** [comment]
@mtgnoah, those issues are the most problematic. Is it a public dataset that I can try to recreate the problem?  

> null-{"type": "trace", "transaction_index": 0,

What is that null at the begging of the message?

**Comment by mtgnoah** [comment]
The key is always null

**Comment by mtgnoah** [comment]
@mzitnik I am just streaming ethereum_blocks, ethereum_transactions, ethereum_logs, and ethereum_traces from this program [link](https://github.com/blockchain-etl/ethereum-etl ) to kafka topics

**Comment by mtgnoah** [comment]
@mzitnik would Decimal(38, 0) have an issue with a value of 0? Does this column need to be nullable?

**Comment by mzitnik** [comment]
> I am just streaming ethereum_blocks, ethereum_transactions, ethereum_logs, and ethereum_traces from this program [link](https://github.com/blockchain-etl/ethereum-etl) to kafka topics

Can you provide an example how do you export the data into Kafka so i could recreate

**Comment by mtgnoah** [comment]
@mzitnik I just use the ethereum-etl program provided above in the link. Currently I am streaming multiple topics with one kafka connect. I am going to attempt using 4 different instances of kakfa connect instead to see if that helps me narrow down the issue.

**Comment by nicolae-gorgias** [comment]
@mzitnik I have the same issue, it crashes randomly, and after restart it continues the sink, maybe it's a valid option to add this exception in the new retry mechanism?

```
ERROR [tracking-events-clickhouse-sink|task-0]  Try to insert 1 rows (com.clickhouse.kafka.connect.sink.db.ClickHouseWriter:377)
java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Unexpected end of file from server, server ClickHouseNode [uri=https://...:8443/revenue_addon, options={sslmode=STRICT}]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
...
```

**Comment by mtgnoah** [comment]
Ok I tried to use 4 instances and it still crashes randomly. It is not using too much ram or anything else I can tell.
