### ISSUE TITLE
Schema insert doesn't handle missing fields when a column has default value

### ISSUE THREAD

**Issue by nicolae-gorgias** [ClickHouse/clickhouse-kafka-connect#94]
### Describe the bug

I am trying to remove a field from the schema registry. After successfully deploying my changes, I attempted to remove the corresponding column from ClickHouse. I expected that once the field was missing and a new insert occurred, it would be populated with its default value. However, the connector crashed instead.

### Steps to reproduce
1. Create a table with two NOT NULL columns and with a default value
2. Declare a schema that contains only one field
3. Try to insert a row

### Expected behavior
The missing field should be populated with his default value, [like for Nullable columns](https://github.com/ClickHouse/clickhouse-kafka-connect/blob/main/src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java#L327). Not sure about the correct approach here, probably populating with default value should be on Clickhouse side then we can just send null for columns which have default value but there are missing in the schema.

### Error log
```
[2023-04-17 15:26:06,519] ERROR [tracking-events-clickhouse-sink|task-1]  Record is missing field integrationId (com.clickhouse.kafka.connect.sink.db.ClickHouseWriter:320)
java.lang.RuntimeException
	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doWriteCol(ClickHouseWriter.java:321)
	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:366)
	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:131)
	at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:45)
	at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:102)
	at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
	at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.RuntimeException
	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertRawBinary(ClickHouseWriter.java:385)
	at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:131)
	at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:45)
	at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:102)
	at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:80)
	at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

#### Example of a table:

```
create table test_table ON CLUSTER '{cluster}'
(
    accountId           Int64,
    integrationId       Int64  DEFAULT 0
)
    engine = ReplicatedMergeTree('/clickhouse/{cluster}/tables/{shard}/{database}/{table}', '{replica}') ORDER BY (accountId);
```

#### Schema

```
{
    type: 'record',
    namespace: 'test',
    name: 'TestTable',
    fields: [
        {
            name: 'accountId',
            type: 'long',
        }
    ],
}
```

#### My SQL expectation in this case

```
INSERT INTO test_table (accountId) values (2);
```
or
```
INSERT INTO test_table (accountId, integrationId) values (2, null);
```

**Comment by nicolae-gorgias** [comment]
@Paultagoras I started a PR for this but [write-null idea fails here](https://github.com/ClickHouse/clickhouse-kafka-connect/pull/100/files#diff-3180bd2c71e5c2af1a2aafe6ba0d52a50da1e97cefc6528911a35dda50c46ed0R332). Do you have any idea why? I expected that it will fill it with null but it skips the column or dont know.

**Comment by nicolae-gorgias** [comment]
@Paultagoras got it
